# Generated by Django 5.2.9 on 2026-01-24 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateclass',
            name='member',
        ),
        migrations.RemoveField(
            model_name='privateclass',
            name='schedule_time',
        ),
        migrations.RemoveField(
            model_name='privateclass',
            name='status',
        ),
        migrations.RemoveField(
            model_name='privateclass',
            name='title',
        ),
        migrations.AddField(
            model_name='privateclass',
            name='duration_hours',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='duration_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='start_date',
            field=models.DateField(default='2026-01-24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privateclass',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privateclass',
            name='user',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'Member'}, on_delete=django.db.models.deletion.CASCADE, related_name='member_private_classes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_private_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
