# Generated by Django 5.2.9 on 2026-01-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_privateclass_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privateclass',
            old_name='user',
            new_name='member',
        ),
    ]
