# Generated by Django 5.2.9 on 2026-01-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_rename_user_privateclass_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateclass',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
