# Generated by Django 5.2.9 on 2026-01-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_privateclass_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
