# Generated by Django 5.2.9 on 2026-01-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_uuid',
            field=models.CharField(blank=True, help_text='eSewa transaction UUID', max_length=100, null=True),
        ),
    ]
