# Generated by Django 5.2.9 on 2026-01-29 16:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_payment_transaction_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_uuid',
        ),
        migrations.AddField(
            model_name='payment',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
