# Generated by Django 5.2.9 on 2026-01-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_remove_payment_transaction_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersubscription',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
